//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietPlanning.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fat
    {
        public int Id { get; set; }
        public Nullable<int> FoodId { get; set; }
        public Nullable<double> BaseFat { get; set; }
        public Nullable<double> BaseSaturatedFat { get; set; }
        public Nullable<double> BaseMonounsaturatedFat { get; set; }
        public Nullable<double> BasePolyunsaturatedFat { get; set; }
        public Nullable<double> BaseTransFattyAcids { get; set; }
        public Nullable<double> BaseTransMonoenoicFatyAcids { get; set; }
        public Nullable<double> BaseTransPolyenoicFatyAcids { get; set; }
        public Nullable<double> BaseOmega3FattyAcids { get; set; }
        public Nullable<double> BaseOmega6FattyAcids { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
