//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietPlanning.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Minerals
    {
        public int Id { get; set; }
        public int FoodId { get; set; }
        public Nullable<double> Calcium { get; set; }
        public Nullable<double> Iron { get; set; }
        public Nullable<double> Magnesium { get; set; }
        public Nullable<double> Phosphorus { get; set; }
        public Nullable<double> Potassium { get; set; }
        public Nullable<double> Sodium { get; set; }
        public Nullable<double> Zinc { get; set; }
        public Nullable<double> Copper { get; set; }
        public Nullable<double> Manganese { get; set; }
        public Nullable<double> Selenium { get; set; }
        public Nullable<double> Fluoride { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
