//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietPlanning.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other
    {
        public int Id { get; set; }
        public int FoodId { get; set; }
        public Nullable<double> Cholesterol { get; set; }
        public Nullable<double> Phytosterols { get; set; }
        public Nullable<double> BaseAlcohol { get; set; }
        public Nullable<double> BaseWater { get; set; }
        public Nullable<double> BaseAsh { get; set; }
        public Nullable<double> Caffeine { get; set; }
        public Nullable<double> Theobromine { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
