//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DietPlanning.Model.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DietPlanning.Model.Localization.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanine.
        /// </summary>
        internal static string Alanine {
            get {
                return ResourceManager.GetString("Alanine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arginine.
        /// </summary>
        internal static string Arginine {
            get {
                return ResourceManager.GetString("Arginine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspartic Acid.
        /// </summary>
        internal static string AsparticAcid {
            get {
                return ResourceManager.GetString("AsparticAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol.
        /// </summary>
        internal static string BaseAlcohol {
            get {
                return ResourceManager.GetString("BaseAlcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ash.
        /// </summary>
        internal static string BaseAsh {
            get {
                return ResourceManager.GetString("BaseAsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrates.
        /// </summary>
        internal static string BaseCarboHydrate {
            get {
                return ResourceManager.GetString("BaseCarboHydrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dietary Fiber.
        /// </summary>
        internal static string BaseDietaryFiber {
            get {
                return ResourceManager.GetString("BaseDietaryFiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        internal static string BaseFat {
            get {
                return ResourceManager.GetString("BaseFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monounsaturated Fat.
        /// </summary>
        internal static string BaseMonounsaturatedFat {
            get {
                return ResourceManager.GetString("BaseMonounsaturatedFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega 3 Fatty Acids.
        /// </summary>
        internal static string BaseOmega3FattyAcids {
            get {
                return ResourceManager.GetString("BaseOmega3FattyAcids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega 6 Fatty Acids.
        /// </summary>
        internal static string BaseOmega6FattyAcids {
            get {
                return ResourceManager.GetString("BaseOmega6FattyAcids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyunsaturated Fat.
        /// </summary>
        internal static string BasePolyunsaturatedFat {
            get {
                return ResourceManager.GetString("BasePolyunsaturatedFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        internal static string BaseProteinContent {
            get {
                return ResourceManager.GetString("BaseProteinContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated Fat.
        /// </summary>
        internal static string BaseSaturatedFat {
            get {
                return ResourceManager.GetString("BaseSaturatedFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starch.
        /// </summary>
        internal static string BaseStarch {
            get {
                return ResourceManager.GetString("BaseStarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugars.
        /// </summary>
        internal static string BaseSugars {
            get {
                return ResourceManager.GetString("BaseSugars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Fatty Acids.
        /// </summary>
        internal static string BaseTransFattyAcids {
            get {
                return ResourceManager.GetString("BaseTransFattyAcids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Monoenoic Faty Acids.
        /// </summary>
        internal static string BaseTransMonoenoicFatyAcids {
            get {
                return ResourceManager.GetString("BaseTransMonoenoicFatyAcids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Polyenoic Faty Acids.
        /// </summary>
        internal static string BaseTransPolyenoicFatyAcids {
            get {
                return ResourceManager.GetString("BaseTransPolyenoicFatyAcids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string BaseWater {
            get {
                return ResourceManager.GetString("BaseWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betaine.
        /// </summary>
        internal static string Betaine {
            get {
                return ResourceManager.GetString("Betaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caffeine.
        /// </summary>
        internal static string Caffeine {
            get {
                return ResourceManager.GetString("Caffeine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium.
        /// </summary>
        internal static string Calcium {
            get {
                return ResourceManager.GetString("Calcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrate.
        /// </summary>
        internal static string Carbohydrate {
            get {
                return ResourceManager.GetString("Carbohydrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        internal static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choline.
        /// </summary>
        internal static string Choline {
            get {
                return ResourceManager.GetString("Choline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        internal static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cystine.
        /// </summary>
        internal static string Cystine {
            get {
                return ResourceManager.GetString("Cystine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        internal static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluoride.
        /// </summary>
        internal static string Fluoride {
            get {
                return ResourceManager.GetString("Fluoride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folate.
        /// </summary>
        internal static string Folate {
            get {
                return ResourceManager.GetString("Folate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolicAcid.
        /// </summary>
        internal static string FolicAcid {
            get {
                return ResourceManager.GetString("FolicAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fructose.
        /// </summary>
        internal static string Fructose {
            get {
                return ResourceManager.GetString("Fructose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galactose.
        /// </summary>
        internal static string Galactose {
            get {
                return ResourceManager.GetString("Galactose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        internal static string Glucose {
            get {
                return ResourceManager.GetString("Glucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glutamic Acid.
        /// </summary>
        internal static string GlutamicAcid {
            get {
                return ResourceManager.GetString("GlutamicAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glycine.
        /// </summary>
        internal static string Glycine {
            get {
                return ResourceManager.GetString("Glycine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histidine.
        /// </summary>
        internal static string Histidine {
            get {
                return ResourceManager.GetString("Histidine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydroxiproline.
        /// </summary>
        internal static string Hydroxiproline {
            get {
                return ResourceManager.GetString("Hydroxiproline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        internal static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isoleucine.
        /// </summary>
        internal static string Isoleucine {
            get {
                return ResourceManager.GetString("Isoleucine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kcal.
        /// </summary>
        internal static string Kcal {
            get {
                return ResourceManager.GetString("Kcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kj.
        /// </summary>
        internal static string Kj {
            get {
                return ResourceManager.GetString("Kj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactose.
        /// </summary>
        internal static string Lactose {
            get {
                return ResourceManager.GetString("Lactose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leucine.
        /// </summary>
        internal static string Leucine {
            get {
                return ResourceManager.GetString("Leucine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lysine.
        /// </summary>
        internal static string Lysine {
            get {
                return ResourceManager.GetString("Lysine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium .
        /// </summary>
        internal static string Magnesium {
            get {
                return ResourceManager.GetString("Magnesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltose.
        /// </summary>
        internal static string Maltose {
            get {
                return ResourceManager.GetString("Maltose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manganese.
        /// </summary>
        internal static string Manganese {
            get {
                return ResourceManager.GetString("Manganese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methionine.
        /// </summary>
        internal static string Methionine {
            get {
                return ResourceManager.GetString("Methionine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minerals.
        /// </summary>
        internal static string Minerals {
            get {
                return ResourceManager.GetString("Minerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niacin.
        /// </summary>
        internal static string Niacin {
            get {
                return ResourceManager.GetString("Niacin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pantothenic Acid.
        /// </summary>
        internal static string PantothenicAcid {
            get {
                return ResourceManager.GetString("PantothenicAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phenylalanine.
        /// </summary>
        internal static string Phenylalanine {
            get {
                return ResourceManager.GetString("Phenylalanine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorus.
        /// </summary>
        internal static string Phosphorus {
            get {
                return ResourceManager.GetString("Phosphorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phytosterols.
        /// </summary>
        internal static string Phytosterols {
            get {
                return ResourceManager.GetString("Phytosterols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        internal static string Potassium {
            get {
                return ResourceManager.GetString("Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proline.
        /// </summary>
        internal static string Proline {
            get {
                return ResourceManager.GetString("Proline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        internal static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riboflavin.
        /// </summary>
        internal static string Riboflavin {
            get {
                return ResourceManager.GetString("Riboflavin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium.
        /// </summary>
        internal static string Selenium {
            get {
                return ResourceManager.GetString("Selenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serine.
        /// </summary>
        internal static string Serine {
            get {
                return ResourceManager.GetString("Serine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        internal static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucrose.
        /// </summary>
        internal static string Sucrose {
            get {
                return ResourceManager.GetString("Sucrose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theobromine.
        /// </summary>
        internal static string Theobromine {
            get {
                return ResourceManager.GetString("Theobromine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiamin.
        /// </summary>
        internal static string Thiamin {
            get {
                return ResourceManager.GetString("Thiamin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threonine.
        /// </summary>
        internal static string Threonine {
            get {
                return ResourceManager.GetString("Threonine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryptophan.
        /// </summary>
        internal static string Tryptophan {
            get {
                return ResourceManager.GetString("Tryptophan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyrosine.
        /// </summary>
        internal static string Tyrosine {
            get {
                return ResourceManager.GetString("Tyrosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valine.
        /// </summary>
        internal static string Valine {
            get {
                return ResourceManager.GetString("Valine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin A.
        /// </summary>
        internal static string VitaminA {
            get {
                return ResourceManager.GetString("VitaminA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B12.
        /// </summary>
        internal static string VitaminB12 {
            get {
                return ResourceManager.GetString("VitaminB12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin B6.
        /// </summary>
        internal static string VitaminB6 {
            get {
                return ResourceManager.GetString("VitaminB6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin C.
        /// </summary>
        internal static string VitaminC {
            get {
                return ResourceManager.GetString("VitaminC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin D.
        /// </summary>
        internal static string VitaminD {
            get {
                return ResourceManager.GetString("VitaminD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin E.
        /// </summary>
        internal static string VitaminE {
            get {
                return ResourceManager.GetString("VitaminE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin K.
        /// </summary>
        internal static string VitaminK {
            get {
                return ResourceManager.GetString("VitaminK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamins.
        /// </summary>
        internal static string Vitamins {
            get {
                return ResourceManager.GetString("Vitamins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zinc.
        /// </summary>
        internal static string Zinc {
            get {
                return ResourceManager.GetString("Zinc", resourceCulture);
            }
        }
    }
}
